apiVersion: v1
kind: Service
metadata:
    name: "dnazureaks-48ae"
    labels:
        app: "dnazureaks-48ae"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "dnazureaks-48ae"